import React, { useState } from 'react';
import { generateTripPlan } from './services/geminiService';
import { TripData, LoadingState } from './types';
import { AnalysisSection } from './components/AnalysisSection';
import { ShowGallery } from './components/ShowGallery';
import { ItineraryTimeline } from './components/ItineraryTimeline';
import { Compass, Loader2, Map, CalendarClock, Info } from 'lucide-react';

const App: React.FC = () => {
  const [data, setData] = useState<TripData | null>(null);
  const [loadingState, setLoadingState] = useState<LoadingState>(LoadingState.IDLE);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    setLoadingState(LoadingState.LOADING);
    setError(null);
    try {
      const result = await generateTripPlan();
      setData(result);
      setLoadingState(LoadingState.SUCCESS);
    } catch (err) {
      console.error(err);
      setError("无法生成攻略，请检查网络或API Key配置。");
      setLoadingState(LoadingState.ERROR);
    }
  };

  return (
    <div className="min-h-screen bg-earth-50 text-earth-900 pb-20">
      {/* Hero Section */}
      <header className="relative bg-earth-800 text-earth-50 py-20 px-6 overflow-hidden">
        <div className="absolute inset-0 opacity-10 bg-[url('https://images.unsplash.com/photo-1516483638261-f4dbaf036963?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80')] bg-cover bg-center mix-blend-overlay"></div>
        <div className="max-w-5xl mx-auto relative z-10 text-center">
          <div className="inline-flex items-center gap-2 bg-earth-700/50 backdrop-blur-sm px-4 py-1.5 rounded-full text-sm font-medium mb-6 border border-earth-600">
            <Map size={16} /> 河南·郑州
          </div>
          <h1 className="text-4xl md:text-6xl font-heading font-bold mb-6 tracking-tight">
            只有河南·戏剧幻城
          </h1>
          <p className="text-xl text-earth-200 max-w-2xl mx-auto mb-10 font-light">
            一座有21个剧场的戏剧幻城，用两天时间，聆听黄土地的低语。
          </p>
          
          {loadingState === LoadingState.IDLE && (
            <button
              onClick={handleGenerate}
              className="group bg-earth-100 text-earth-900 hover:bg-white transition-all px-8 py-4 rounded-full font-bold text-lg flex items-center gap-3 mx-auto shadow-lg hover:shadow-xl hover:scale-105 active:scale-95"
            >
              <Compass className="group-hover:rotate-45 transition-transform" />
              生成两日全攻略
            </button>
          )}

          {loadingState === LoadingState.LOADING && (
            <div className="flex flex-col items-center justify-center text-earth-200">
              <Loader2 className="animate-spin mb-4" size={32} />
              <p>AI 正在规划最佳观演路线...</p>
            </div>
          )}
          
          {loadingState === LoadingState.ERROR && (
             <div className="bg-red-900/50 border border-red-700 text-white p-4 rounded-lg inline-block">
               <p>{error}</p>
               <button onClick={handleGenerate} className="mt-2 underline text-sm hover:text-earth-200">重试</button>
             </div>
          )}
        </div>
      </header>

      {/* Main Content */}
      {data && loadingState === LoadingState.SUCCESS && (
        <main className="max-w-6xl mx-auto px-4 sm:px-6 -mt-10 relative z-20">
          
          {/* Analysis Section */}
          <AnalysisSection data={data.analysis} />

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            {/* Left Column: Itinerary (taking up more space) */}
            <div className="lg:col-span-7 space-y-8">
               <div className="flex items-center gap-3 mb-2">
                <CalendarClock className="text-earth-700" size={24} />
                <h2 className="text-2xl font-heading font-bold text-earth-900">两日观演行程</h2>
              </div>
              <ItineraryTimeline days={data.itinerary} />
            </div>

            {/* Right Column: Shows List */}
            <div className="lg:col-span-5 space-y-8">
              <div className="flex items-center gap-3 mb-2">
                <Info className="text-earth-700" size={24} />
                <h2 className="text-2xl font-heading font-bold text-earth-900">剧目指南</h2>
              </div>
              <ShowGallery shows={data.shows} />
            </div>
          </div>
        </main>
      )}

      {/* Footer */}
      <footer className="max-w-6xl mx-auto px-6 mt-20 text-center text-earth-500 text-sm">
        <p>Generated by Gemini AI • 仅供参考，具体演出时间以景区当日公示为准</p>
      </footer>
    </div>
  );
};

export default App;